-- Color-Wall colorscheme - auto-generated from wallpaper
-- Generated by: dotfiles theme generate

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
	vim.cmd("syntax reset")
end

vim.g.colors_name = "color-wall"
vim.o.termguicolors = true
vim.o.background = "dark"

local c = {
	-- Base colors
	bg = "#09131a",
	bg_dark = "#030a10",
	bg_light = "#172128",
	bg_visual = "#1b2b36",
	fg = "#d8dfe4",
	fg_dark = "#999fa4",
	fg_gutter = "#3e4952",

	-- Accent colors
	coral = "#d57abd",
	coral_bright = "#f799dd",
	teal = "#00a9a3",
	teal_bright = "#00c9c3",
	orange = "#adb742",
	gold = "#b4df78",
	magenta = "#9b8ff0",
	pink = "#cba8ff",
	cyan = "#00c4e1",
	blue = "#36a8ec",
	navy = "#082530",

	-- Semantic colors
	error = "#e7729b",
	warn = "#fac547",
	info = "#00c9d3",
	hint = "#36a8ec",
	success = "#6bc670",

	-- UI colors
	border = "#293e47",
	selection = "#1b2b36",
	comment = "#4b6875",
	none = "NONE",
}

local hl = function(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

-- Editor (transparent)
hl("Normal", { fg = c.fg, bg = c.none })
hl("NormalFloat", { fg = c.fg, bg = c.bg_dark })
hl("FloatBorder", { fg = c.border, bg = c.bg_dark })
hl("Cursor", { fg = c.bg, bg = c.fg })
hl("CursorLine", { bg = c.bg_light })
hl("CursorColumn", { bg = c.bg_light })
hl("ColorColumn", { bg = c.bg_light })
hl("LineNr", { fg = c.fg_gutter })
hl("CursorLineNr", { fg = c.orange, bold = true })
hl("SignColumn", { fg = c.fg_gutter, bg = c.none })
hl("VertSplit", { fg = c.border })
hl("WinSeparator", { fg = c.border })
hl("Folded", { fg = c.comment, bg = c.bg_light })
hl("FoldColumn", { fg = c.comment })
hl("NonText", { fg = c.fg_gutter })
hl("SpecialKey", { fg = c.fg_gutter })
hl("Whitespace", { fg = c.fg_gutter })
hl("EndOfBuffer", { fg = c.none })

-- Search & Selection
hl("Search", { fg = c.bg, bg = c.orange })
hl("IncSearch", { fg = c.bg, bg = c.coral })
hl("CurSearch", { fg = c.bg, bg = c.coral_bright })
hl("Visual", { bg = c.bg_visual })
hl("VisualNOS", { bg = c.bg_visual })

-- Popup menu
hl("Pmenu", { fg = c.fg, bg = c.bg_dark })
hl("PmenuSel", { fg = c.fg, bg = c.selection })
hl("PmenuSbar", { bg = c.bg_light })
hl("PmenuThumb", { bg = c.border })

-- Messages
hl("ErrorMsg", { fg = c.error })
hl("WarningMsg", { fg = c.warn })
hl("ModeMsg", { fg = c.fg, bold = true })
hl("MoreMsg", { fg = c.teal })
hl("Question", { fg = c.teal })

-- Tabs
hl("TabLine", { fg = c.fg_dark, bg = c.none })
hl("TabLineFill", { bg = c.none })
hl("TabLineSel", { fg = c.fg, bg = c.bg_light })

-- Status line
hl("StatusLine", { fg = c.fg, bg = c.none })
hl("StatusLineNC", { fg = c.fg_dark, bg = c.none })

-- Diff
hl("DiffAdd", { fg = c.success, bg = "#0a2828" })
hl("DiffChange", { fg = c.orange, bg = "#1a2a1a" })
hl("DiffDelete", { fg = c.error, bg = "#2a1a1a" })
hl("DiffText", { fg = c.orange, bg = "#2a3a2a" })

-- Spelling
hl("SpellBad", { sp = c.error, undercurl = true })
hl("SpellCap", { sp = c.warn, undercurl = true })
hl("SpellLocal", { sp = c.info, undercurl = true })
hl("SpellRare", { sp = c.hint, undercurl = true })

-- Syntax
hl("Comment", { fg = c.comment, italic = true })
hl("Constant", { fg = c.cyan })
hl("String", { fg = c.teal })
hl("Character", { fg = c.teal_bright })
hl("Number", { fg = c.coral })
hl("Boolean", { fg = c.coral })
hl("Float", { fg = c.coral })

hl("Identifier", { fg = c.fg })
hl("Function", { fg = c.orange })

hl("Statement", { fg = c.magenta })
hl("Conditional", { fg = c.magenta })
hl("Repeat", { fg = c.magenta })
hl("Label", { fg = c.magenta })
hl("Operator", { fg = c.pink })
hl("Keyword", { fg = c.magenta })
hl("Exception", { fg = c.magenta })

hl("PreProc", { fg = c.cyan })
hl("Include", { fg = c.magenta })
hl("Define", { fg = c.magenta })
hl("Macro", { fg = c.cyan })
hl("PreCondit", { fg = c.cyan })

hl("Type", { fg = c.cyan })
hl("StorageClass", { fg = c.magenta })
hl("Structure", { fg = c.cyan })
hl("Typedef", { fg = c.cyan })

hl("Special", { fg = c.orange })
hl("SpecialChar", { fg = c.orange })
hl("Tag", { fg = c.orange })
hl("Delimiter", { fg = c.fg_dark })
hl("SpecialComment", { fg = c.comment })
hl("Debug", { fg = c.coral })

hl("Underlined", { fg = c.blue, underline = true })
hl("Ignore", { fg = c.fg_gutter })
hl("Error", { fg = c.error })
hl("Todo", { fg = c.bg, bg = c.orange, bold = true })

-- Treesitter
hl("@variable", { fg = c.fg })
hl("@variable.builtin", { fg = c.coral })
hl("@variable.parameter", { fg = c.fg_dark })
hl("@variable.member", { fg = c.blue })

hl("@constant", { fg = c.cyan })
hl("@constant.builtin", { fg = c.coral })
hl("@constant.macro", { fg = c.cyan })

hl("@module", { fg = c.cyan })
hl("@label", { fg = c.magenta })

hl("@string", { fg = c.teal })
hl("@string.escape", { fg = c.teal_bright })
hl("@string.special", { fg = c.teal_bright })

hl("@character", { fg = c.teal_bright })
hl("@number", { fg = c.coral })
hl("@boolean", { fg = c.coral })
hl("@float", { fg = c.coral })

hl("@function", { fg = c.orange })
hl("@function.builtin", { fg = c.gold })
hl("@function.call", { fg = c.orange })
hl("@function.macro", { fg = c.cyan })
hl("@function.method", { fg = c.orange })
hl("@function.method.call", { fg = c.orange })

hl("@constructor", { fg = c.cyan })
hl("@operator", { fg = c.pink })

hl("@keyword", { fg = c.magenta })
hl("@keyword.function", { fg = c.magenta })
hl("@keyword.operator", { fg = c.pink })
hl("@keyword.import", { fg = c.magenta })
hl("@keyword.return", { fg = c.magenta })
hl("@keyword.exception", { fg = c.magenta })

hl("@type", { fg = c.cyan })
hl("@type.builtin", { fg = c.cyan })
hl("@type.qualifier", { fg = c.magenta })

hl("@attribute", { fg = c.cyan })
hl("@property", { fg = c.blue })

hl("@comment", { fg = c.comment, italic = true })
hl("@comment.todo", { fg = c.bg, bg = c.orange, bold = true })
hl("@comment.warning", { fg = c.bg, bg = c.warn })
hl("@comment.error", { fg = c.bg, bg = c.error })
hl("@comment.note", { fg = c.bg, bg = c.info })

hl("@punctuation.bracket", { fg = c.fg_dark })
hl("@punctuation.delimiter", { fg = c.fg_dark })
hl("@punctuation.special", { fg = c.pink })

hl("@tag", { fg = c.orange })
hl("@tag.attribute", { fg = c.cyan })
hl("@tag.delimiter", { fg = c.fg_dark })

hl("@markup.heading", { fg = c.orange, bold = true })
hl("@markup.strong", { bold = true })
hl("@markup.italic", { italic = true })
hl("@markup.strikethrough", { strikethrough = true })
hl("@markup.underline", { underline = true })
hl("@markup.link", { fg = c.blue })
hl("@markup.link.url", { fg = c.teal, underline = true })
hl("@markup.raw", { fg = c.teal })
hl("@markup.list", { fg = c.pink })

-- LSP
hl("DiagnosticError", { fg = c.error })
hl("DiagnosticWarn", { fg = c.warn })
hl("DiagnosticInfo", { fg = c.info })
hl("DiagnosticHint", { fg = c.hint })

hl("DiagnosticUnderlineError", { sp = c.error, undercurl = true })
hl("DiagnosticUnderlineWarn", { sp = c.warn, undercurl = true })
hl("DiagnosticUnderlineInfo", { sp = c.info, undercurl = true })
hl("DiagnosticUnderlineHint", { sp = c.hint, undercurl = true })

hl("LspReferenceText", { bg = c.selection })
hl("LspReferenceRead", { bg = c.selection })
hl("LspReferenceWrite", { bg = c.selection })

-- Git signs
hl("GitSignsAdd", { fg = c.success })
hl("GitSignsChange", { fg = c.orange })
hl("GitSignsDelete", { fg = c.error })

-- Telescope
hl("TelescopeNormal", { fg = c.fg, bg = c.bg_dark })
hl("TelescopeBorder", { fg = c.border, bg = c.bg_dark })
hl("TelescopePromptNormal", { fg = c.fg, bg = c.bg_light })
hl("TelescopePromptBorder", { fg = c.bg_light, bg = c.bg_light })
hl("TelescopePromptTitle", { fg = c.bg, bg = c.orange })
hl("TelescopePreviewTitle", { fg = c.bg, bg = c.teal })
hl("TelescopeResultsTitle", { fg = c.bg, bg = c.magenta })
hl("TelescopeSelection", { bg = c.selection })
hl("TelescopeMatching", { fg = c.coral, bold = true })

-- Neo-tree
hl("NeoTreeNormal", { fg = c.fg, bg = c.none })
hl("NeoTreeNormalNC", { fg = c.fg, bg = c.none })
hl("NeoTreeDirectoryName", { fg = c.blue })
hl("NeoTreeDirectoryIcon", { fg = c.blue })
hl("NeoTreeRootName", { fg = c.orange, bold = true })
hl("NeoTreeFileName", { fg = c.fg })
hl("NeoTreeGitAdded", { fg = c.success })
hl("NeoTreeGitModified", { fg = c.orange })
hl("NeoTreeGitDeleted", { fg = c.error })
hl("NeoTreeGitUntracked", { fg = c.magenta })
hl("NeoTreeFloatBorder", { fg = c.border, bg = c.bg_dark })
hl("NeoTreeFloatNormal", { fg = c.fg, bg = c.bg_dark })
hl("NeoTreeWinSeparator", { fg = c.border, bg = c.none })
hl("NeoTreeEndOfBuffer", { fg = c.bg_dark, bg = c.bg_dark })

-- Which-key
hl("WhichKey", { fg = c.orange })
hl("WhichKeyGroup", { fg = c.magenta })
hl("WhichKeyDesc", { fg = c.fg })
hl("WhichKeySeparator", { fg = c.comment })
hl("WhichKeyFloat", { bg = c.bg_dark })

-- Lazy.nvim
hl("LazyH1", { fg = c.bg, bg = c.orange, bold = true })
hl("LazyButton", { fg = c.fg, bg = c.bg_light })
hl("LazyButtonActive", { fg = c.bg, bg = c.orange })
hl("LazySpecial", { fg = c.cyan })
hl("LazyProgressDone", { fg = c.teal })
hl("LazyProgressTodo", { fg = c.fg_gutter })

-- Diagnostic virtual text
hl("DiagnosticVirtualTextError", { fg = c.error, bg = "#1a1020" })
hl("DiagnosticVirtualTextWarn", { fg = c.warn, bg = "#1a1a10" })
hl("DiagnosticVirtualTextInfo", { fg = c.info, bg = "#101a1a" })
hl("DiagnosticVirtualTextHint", { fg = c.hint, bg = "#10101a" })

-- LSP
hl("LspSignatureActiveParameter", { fg = c.orange, bold = true })
hl("LspInlayHint", { fg = c.comment, bg = c.bg_light })

-- Indent guides
hl("IndentBlanklineChar", { fg = c.fg_gutter })
hl("IndentBlanklineContextChar", { fg = c.border })
hl("IblIndent", { fg = c.fg_gutter })
hl("IblScope", { fg = c.border })

-- Noice
hl("NoiceCmdlinePopup", { fg = c.fg, bg = c.bg_dark })
hl("NoiceCmdlinePopupBorder", { fg = c.border, bg = c.bg_dark })
hl("NoiceCmdlineIcon", { fg = c.orange })
hl("NoiceCmdline", { fg = c.fg, bg = c.bg_dark })
hl("NoiceCmdlinePopupTitle", { fg = c.bg, bg = c.orange })
hl("NoicePopup", { fg = c.fg, bg = c.bg_dark })
hl("NoicePopupBorder", { fg = c.border, bg = c.bg_dark })

-- Notify
hl("NotifyERRORBorder", { fg = c.error })
hl("NotifyWARNBorder", { fg = c.warn })
hl("NotifyINFOBorder", { fg = c.info })
hl("NotifyDEBUGBorder", { fg = c.comment })
hl("NotifyTRACEBorder", { fg = c.hint })
hl("NotifyERRORIcon", { fg = c.error })
hl("NotifyWARNIcon", { fg = c.warn })
hl("NotifyINFOIcon", { fg = c.info })
hl("NotifyDEBUGIcon", { fg = c.comment })
hl("NotifyTRACEIcon", { fg = c.hint })
hl("NotifyERRORTitle", { fg = c.error })
hl("NotifyWARNTitle", { fg = c.warn })
hl("NotifyINFOTitle", { fg = c.info })
hl("NotifyDEBUGTitle", { fg = c.comment })
hl("NotifyTRACETitle", { fg = c.hint })

-- Cmp (completion)
hl("CmpItemAbbr", { fg = c.fg })
hl("CmpItemAbbrMatch", { fg = c.coral, bold = true })
hl("CmpItemAbbrMatchFuzzy", { fg = c.coral })
hl("CmpItemAbbrDeprecated", { fg = c.comment, strikethrough = true })
hl("CmpItemKind", { fg = c.orange })
hl("CmpItemMenu", { fg = c.comment })

-- Blink.cmp
hl("BlinkCmpMenu", { fg = c.fg, bg = c.bg_dark })
hl("BlinkCmpMenuBorder", { fg = c.border, bg = c.bg_dark })
hl("BlinkCmpMenuSelection", { bg = c.selection })
hl("BlinkCmpLabel", { fg = c.fg })
hl("BlinkCmpLabelMatch", { fg = c.coral, bold = true })
hl("BlinkCmpKind", { fg = c.orange })

-- Dashboard / Alpha
hl("DashboardHeader", { fg = c.coral })
hl("DashboardCenter", { fg = c.orange })
hl("DashboardFooter", { fg = c.comment })
hl("DashboardShortcut", { fg = c.cyan })

-- Mason
hl("MasonHeader", { fg = c.bg, bg = c.orange, bold = true })
hl("MasonHighlight", { fg = c.cyan })
hl("MasonHighlightBlock", { fg = c.bg, bg = c.teal })
hl("MasonHighlightBlockBold", { fg = c.bg, bg = c.teal, bold = true })
hl("MasonMuted", { fg = c.comment })
hl("MasonMutedBlock", { fg = c.fg, bg = c.bg_light })

-- Copilot
hl("CopilotSuggestion", { fg = c.comment, italic = true })
hl("CopilotAnnotation", { fg = c.comment })

-- Mini
hl("MiniIndentscopeSymbol", { fg = c.border })
hl("MiniSurround", { fg = c.bg, bg = c.orange })

-- Mini.files
hl("MiniFilesBorder", { fg = c.border, bg = c.bg_dark })
hl("MiniFilesBorderModified", { fg = c.orange, bg = c.bg_dark })
hl("MiniFilesCursorLine", { bg = c.selection })
hl("MiniFilesDirectory", { fg = c.blue })
hl("MiniFilesFile", { fg = c.fg })
hl("MiniFilesNormal", { fg = c.fg, bg = c.bg_dark })
hl("MiniFilesTitle", { fg = c.orange, bg = c.bg_dark, bold = true })
hl("MiniFilesTitleFocused", { fg = c.bg, bg = c.orange, bold = true })

-- Snacks
hl("SnacksIndent", { fg = c.fg_gutter })
hl("SnacksIndentScope", { fg = c.border })
